### PR TITLE
added support for PyTest (unit testing)

### PR DESCRIPTION
**Pull request by natemellendorf**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

Adding support for PyTest / unit testing for Python.

### Description

Adding support for PyTest / unit testing for Python.

### CODE REVIEW

**Comment by natemellendorf** [comment]
I wouldn't consider this perfect, but it's a decent place to start for PyTest.
The reason, is because PyTest requires that your python packages all be installed before running it. However, your test_(star).py may have a different set of dependencies than your actual code. 

Example: You need Moto to mock all your AWS requests to Boto3. To work around this, I have the orb install all packages found in a test_requirements.txt and then run PyTest. This means you can't (for now) just point pytest at the project root and pull the trigger. You could, if you place a test_(star).py which includes all packages for all python files within the scope of the repo.

Here's what that looks like in a projects CircleCI config file:
```
workflows:
  version: 2

  linting:
    jobs:
      - prebuild-orb/python_test:
          test-dir: ./cmd/lambda/acctmgmt
          filters:
            branches:
              ignore: master
      - prebuild-orb/python_test:
          test-dir: ./cmd/lambda/account
          filters:
            branches:
              ignore: master
      - prebuild-orb/python_test:
          test-dir: ./cmd/lambda/client
          filters:
            branches:
              ignore: master
       
```

**Comment by murraybutler** [comment]
You could structure the directory to have a "test" directory, store all tests in there and use a separate dev_requirements.txt in that directory and load that in test.  The ORB would then always search for a "test" directory and load dev_requirements.txt, if it wasn't there, it would just fail.

**Review by murraybutler — DISMISSED** [review]
LGTM, I might make the default directory "test" or "cmd/test" or "src/test".
Otherwise, looks solid.

**Review by Japeth — DISMISSED** [review]
LGTM

**Comment by natemellendorf** [comment]
> You could structure the directory to have a "test" directory, store all tests in there and use a separate dev_requirements.txt in that directory and load that in test. The ORB would then always search for a "test" directory and load dev_requirements.txt, if it wasn't there, it would just fail.

@murraybutler 
Sounds good. I may tweak that in just a few.
A single dir with all the test_ files inside, which will contain a single requirements.txt for all the required packages.

**Comment by natemellendorf** [comment]
@murraybutler Ok, updated to reflect what I think you're suggesting. Confirmed that this works.

**Review by murraybutler — APPROVED** [review]
Nice!!!

**Pull request merged**
